# Generated by Django 4.0 on 2024-08-09 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, null=True)),
                ('userName', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('userType', models.IntegerField(choices=[(1, 'student'), (2, 'Staff')], null=True)),
                ('deviceToken', models.CharField(max_length=255, null=True)),
                ('profileImage', models.CharField(max_length=255, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('submittedBy', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=250)),
                ('submittedBy', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courceName', models.CharField(max_length=255, null=True)),
                ('semester', models.CharField(max_length=255)),
                ('classs', models.CharField(max_length=255)),
                ('lectureHours', models.IntegerField()),
                ('submittedBy', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departmentId', models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, related_name='departmentId_ref', to='authAPIs.department')),
            ],
            options={
                'db_table': 'courcess',
            },
        ),
        migrations.CreateModel(
            name='AttendenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('submittedBy', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('courceId', models.ForeignKey(db_column='courceId', on_delete=django.db.models.deletion.CASCADE, related_name='courceId_ref', to='authAPIs.cource')),
                ('studentId', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='studentId_ref', to='authAPIs.user')),
            ],
            options={
                'db_table': 'attendence_logs',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fullName'], name='users_fullNam_5219d7_idx'),
        ),
    ]
